package com.idc.cxf.isp.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.idc.cxf.isp.service.IEventService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-06T09:40:08.778+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ispEventService", 
                  wsdlLocation = "http://localhost:8080/idc/webService/isp_publish?wsdl",
                  targetNamespace = "http://impl.service.isp.cxf.idc.com/") 
public class IspEventService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.isp.cxf.idc.com/", "ispEventService");
    public final static QName EventServiceImplPort = new QName("http://impl.service.isp.cxf.idc.com/", "EventServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/idc/webService/isp_publish?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IspEventService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/idc/webService/isp_publish?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IspEventService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IspEventService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IspEventService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IspEventService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IspEventService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IspEventService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IEventService
     */
    @WebEndpoint(name = "EventServiceImplPort")
    public IEventService getEventServiceImplPort() {
        return super.getPort(EventServiceImplPort, IEventService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEventService
     */
    @WebEndpoint(name = "EventServiceImplPort")
    public IEventService getEventServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EventServiceImplPort, IEventService.class, features);
    }

}
