package com.idc.cxf.isp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-06T09:40:08.717+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://service.isp.cxf.idc.com/", name = "IEventService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEventService {

    @WebMethod
    @RequestWrapper(localName = "createISPEventService", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.CreateISPEventService")
    @ResponseWrapper(localName = "createISPEventServiceResponse", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.CreateISPEventServiceResponse")
    @WebResult(name = "result", targetNamespace = "")
    java.lang.String createISPEventService(
            @WebParam(name = "xmlContent", targetNamespace = "")
                    java.lang.String xmlContent,
            @WebParam(name = "suffixAliasName", targetNamespace = "")
                    java.lang.String suffixAliasName
    );

    @WebMethod
    @RequestWrapper(localName = "xmlToFile", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.XmlToFile")
    @ResponseWrapper(localName = "xmlToFileResponse", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.XmlToFileResponse")
    @WebResult(name = "result", targetNamespace = "")
    java.lang.String xmlToFile(
            @WebParam(name = "xmlContent", targetNamespace = "")
                    java.lang.String xmlContent,
            @WebParam(name = "directory", targetNamespace = "")
                    java.lang.String directory,
            @WebParam(name = "suffixAliasName", targetNamespace = "")
                    java.lang.String suffixAliasName
    );

    @WebMethod(operationName = "addition_yyyy")
    @RequestWrapper(localName = "addition_yyyy", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.AdditionYyyy")
    @ResponseWrapper(localName = "addition_yyyyResponse", targetNamespace = "http://service.isp.cxf.idc.com/", className = "com.idc.cxf.isp.service.AdditionYyyyResponse")
    @WebResult(name = "return", targetNamespace = "")
    int additionYyyy(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1
    );
}
